const actionTypes = {
    CHANGE_VARIABLE: 'CHANGE_VARIABLE',
    CHANGE_N_ROWS: 'CHANGE_N_ROWS',
    RECEIVE_VARIABLE_DATA: 'RECEIVE_VARIABLE_DATA',
    REQUESTING_VARIABLE_DATA: 'REQUESTING_VARIABLE_DATA'
};

export default actionTypes;